; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Wed Jun 13 2018 17:31:36 GMT-0400 (Eastern Daylight Time)
M561 ; clear any bed transform
; Probe the bed at 4 points
G30 P0 X15 Y15 H0 Z-99999
G30 P1 X15 Y215 H0 Z-99999
G30 P2 X228 Y215 H0 Z-99999
G30 P3 X228 Y15 H0 Z-99999 S