; tpost3.g
; called after tool 3 has been selected
;
; generated by RepRapFirmware Configuration Tool on Thu Jun 14 2018 11:41:54 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P3